from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    
    path('why_rbs_international/', views.why_rbs_international, name='why_rbs_international'),
    path('corporate_service_providers/', views.corporate_service_providers, name='corporate_service_providers'),
    path('real_estate_finance/', views.real_estate_finance, name='real_estate_finance'),
    path('private_equity/', views.private_equity, name='private_equity'),
    path('asset_management/', views.asset_management, name='asset_management'),
    path('private_debt/', views.private_debt, name='private_debt'),
    path('infrastructure_renewables/', views.infrastructure_renewables, name='infrastructure_renewables'),
    path('where_we_are/', views.where_we_are, name='where_we_are'),
    path('jersey/', views.jersey, name='jersey'),
    path('guernsey/', views.guernsey, name='guernsey'),
    path('gibraltar/', views.gibraltar, name='gibraltar'),
    path('isle_of_man/', views.isle_of_man, name='isle_of_man'),
    path('luxembourg/', views.luxembourg, name='luxembourg'),
    path('london/', views.london, name='london'),
    path('what_we_do/', views.what_we_do, name='what_we_do'),
    path('bank_accounts_overdrafts/', views.bank_accounts_overdrafts, name='bank_accounts_overdrafts'),
    path('cash_management/', views.cash_management, name='cash_management'),
    path('cards_payments/', views.cards_payments, name='cards_payments'),
    path('financing/', views.financing, name='financing'),
    path('sustainable_finance/', views.sustainable_finance, name='sustainable_finance'),
    path('depositary_services/', views.depositary_services, name='depositary_services'),
    path('markets/', views.markets, name='markets'),
    path('foreign_exchange/', views.foreign_exchange, name='foreign_exchange'),
    path('money_market_deposits/', views.money_market_deposits, name='money_market_deposits'),
    path('notice_deposits/', views.notice_deposits, name='notice_deposits'),
    path('insights/', views.insights, name='insights'),
    path('news/', views.news, name='news'),
    path('eq_digital_banking', views.eq_digital_banking, name='eq_digital_banking'),
    path('eq_online_banking/', views.eq_online_banking, name='eq_online_banking'),
    path('eq_mobile/', views.eq_mobile, name='eq_mobile'),
    path('eq_account_opening/', views.eq_account_opening, name='eq_account_opening'),
    path('eq_support_centre/', views.eq_support_centre, name='eq_support_centre'),
    path('smartcard_and_reader_support_for_eq/', views.smartcard_and_reader_support_for_eq, name='smartcard_and_reader_support_for_eq'),
    path('help_support/', views.help_support, name='help_support'),
    path('fraud_security/', views.fraud_security, name='fraud_security'),
    path('debit_card_payment_support/', views.debit_card_payment_support, name='debit_card_payment_support'),
    path('report_a_fraud_or_scam/', views.report_a_fraud_or_scam, name='report_a_fraud_or_scam'),
    path('corporate_account_reclaims/', views.corporate_account_reclaims, name='corporate_account_reclaims'),
    path('make_a_change_to_your_account/', views.make_a_change_to_your_account, name='make_a_change_to_your_account'),
    path('results_centre/', views.results_centre, name='results_centre'),
    path('bank_base_rate/', views.bank_base_rate, name='bank_base_rate'),
    path('key_information_document_for_priips', views.key_information_document_for_priips, name='key_information_document_for_priips'),
    path('how_automatic_exchange_of_tax_information_affects_you/', views.how_automatic_exchange_of_tax_information_affects_you, name='how_automatic_exchange_of_tax_information_affects_you'),
    path('account_fees_and_charges/', views.account_fees_and_charges, name='account_fees_and_charges'),
    path('payment_services_directive2/', views.payment_services_directive2, name='payment_services_directive2'),
    path('luxembourg_intermediate_ownership_changes/', views.luxembourg_intermediate_ownership_changes, name='luxembourg_intermediate_ownership_changes'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('how_to_make_a_complaint/', views.how_to_make_a_complaint, name='how_to_make_a_complaint'),
    path('leave_us_feedback/', views.leave_us_feedback, name='leave_us_feedback'),
    path('nominate_a_member_of_staff/', views.nominate_a_member_of_staff, name='nominate_a_member_of_staff'),
    
    
    
    
]
